### PR TITLE
Fix style issues

### PR DESCRIPTION
**Pull request by zakkak**
Style issues introduced by https://github.com/graalvm/graalvm-community-jdk21u/pull/4

See https://github.com/graalvm/graalvm-community-jdk21u/actions/runs/10476438513/job/29015316031#step:14:1589

### CODE REVIEW

**Comment by zakkak** [comment]
@simonis or @jerboaa could you please review?

**Review by jerboaa — APPROVED** [review]
LGTM. Seem like there are truffle failures, but that's a different fix.

**Review by simonis — APPROVED** [review]
Looks good to me. Thanks for fixing!

**Comment by simonis** [comment]
> LGTM. Seem like there are truffle failures, but that's a different fix.

This looks like [JDK-8316304](https://bugs.openjdk.org/browse/JDK-8316304) which was downported to JDK 21.0.2. It requires https://github.com/oracle/graal/pull/8239 which I thought we already have downported, but apparently not. I'll take a look and do the downport.

See https://github.com/graalvm/graalvm-community-jdk21u/pull/1#issuecomment-2003858085

**Comment by jerboaa** [comment]
> > LGTM. Seem like there are truffle failures, but that's a different fix.
> 
> This looks like [JDK-8316304](https://bugs.openjdk.org/browse/JDK-8316304) which was downported to JDK 21.0.2. It requires [oracle/graal#8239](https://github.com/oracle/graal/pull/8239) which I thought we already have downported, but apparently not. I'll take a look and do the downport.

Great! Thank you.

**Comment by zakkak** [comment]
Superseded by https://github.com/graalvm/graalvm-community-jdk21u/pull/6

**Pull request closed without merging**
